_: {
  imports = [
    ./stylix
    ../hyprland
    ../required
    ../waybar
    ../btop.nix
    ../fuzzel.nix
    ../gimp.nix
    ../helix.nix
    ../homeDirs.nix
    ../jujutsu.nix
    ../kitty.nix
    ../librewolf.nix
    ../lutris.nix
    ../mako.nix
    ../mpv.nix
    ../nh.nix
    ../nixos-anywhere.nix
    ../qbittorrent.nix
    ../satty.nix
    ../ssh.nix
    ../starship.nix
    ../tor-browser.nix
    ../unar.nix
    ../vesktop.nix
    ../yazi.nix
    ../zsh.nix
  ];
}
